config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "home/about" => 'homes#about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'books/new'
  get "top" => "books#top"
  get "users/:id/follows" => "relationships#follows", as: "follows"
  get "users/:id/followers" => "relationships#followers", as: "followers"
  post 'relationships/:id' => 'relationships#create', as: 'relationships'#user_isとfolloewd_idが結びついたもの,
  get "search" => "users#search", as: "search"

  resources :users, only: [:show, :new, :create, :index, :destroy, :update, :edit]
  resources :relationships, only: [:destroy,]

  resources :books, only: [:new, :create, :index, :edit, :show, :destroy, :update] do
  	resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :home, only: [:top, :about]

end

app/models/user.rb
class User < ApplicationRecord
    devise  :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

    validates :name, length: { in: 2..20 }
    validates :introduction, length: { maximum: 50 }

    has_many :books, dependent: :destroy
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy#外部キーで指定しないとfollowerかfollowedどちらを取るか区別できない。
    has_many :followered, class_name: "Relationship", foreign_key: "followered_id", dependent: :destroy#フォロワー取得
    has_many :following_user, through: :follower, source: :followered # 自分がフォローしている人,through relationships??
    has_many :followered_user, through: :followered, source: :follower # 自分をフォローしている人 following?follower?

    def follow(user_id)
        follower.create(followered_id: user_id)#ユーザーをフォローする
    end


    def unfollow(user_id)
        follower.find_by(followered_id: user_id).destroy#ユーザーのフォローを外す
    end


    def following?(user)
        following_user.include?(user)#フォローしていればtrueを返す
    #binding.pry
    end

    def User.search(search, user_or_book, how_search)
        if user_or_book == "1"
            if how_search == "1"
                User.where(["name LIKE ?", "%#{search}%"])
            elsif how_search == "2"
                User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "3"
                User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "4"
                User.where(['name LIKE ?', "#{search}"])
            else

                User.all
            end
        end
    end




    attachment :profile_image

    enum gender: { man: 0, woman: 1, other: 2}

    enum prefecture: {
    "--未選択--":0,北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

    enum age: { "0歳": 0, "1歳": 1, "2歳": 2, "3歳":3,}



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]

    def  new
            @book = Book.new
            @books = Book.all
    end

    def create
            book = Book.new(book_params)
            book.save
            redirect_to book_path(@book.id)
    end

    def index
            @users = User.all
            @book = Book.new
            @q = User.ransack(params[:q])
            @users = @q.result(distinct: true)
    end

    def show
            @user = User.find(params[:id])
            @book = Book.new
    end

    def edit
            @user = User.find(params[:id])
            if @user != current_user
            redirect_to user_path(current_user.id)
            end
    end

    def update
            @user = User.find(params[:id])
            if  @user.update(user_params)
            redirect_to user_path(@user.id)
            flash[:notice] = "You have updated user successfully."
            else
            render action: :edit
            end
    end

    def destroy
    end

    def search
            @user_or_book = params[:option]
            @how_search = params[:choice]
            if @user_or_book == "1"
            @users = User.search(params[:search], @user_or_book,@how_search)#引数（パラメーター）を3つをモデルに渡す。
            else
            @books = Book.search(params[:search], @user_or_book,@how_search)
            end

    end

    private
        def user_params
            params.require(:user).permit(:name, :profile_image, :introduction,:gender, :address, :prefecture, :age)
        end

        def correct_user
            @user = User.find(params[:id])
            if current_user != @user
            redirect_to user_path(current_user)
            end
        end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_prof.html.erb
<div class = "col-xs-3">
  <h2>User info</h2>
    <div class="profile-container"><br>
      <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", class: "img-circle pull-left profile-img" %>
        <table class="table">
          <tbody>
            <tr></tr> 
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
              <th></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
              <th></th>
              </tr>
          </tbody>
        </table>
          <% if current_user.id == current_user.id %>
            <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
          <% end %>
    </div><br>

  <h2>New book</h2>
    <%= form_for(book) do |f| %>
  <h4>Title</h4>
    <%= f.text_field :title %>
  <h4>Body</h4>
    <%= f.text_area :body %><br>
    <%= f.submit "Create Book" %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <% end %>
</div>

app/views/users/edit.html.erb
<body>
<div class="body">
<div class="container">
<p id="notice"></p>
<h2 class="form-header-title">User info</h2>
    <div class="form-body">
    <%= form_for(@user) do |f| %>
    <div class="field">
    <label for="user_name">Name</label>
   <%= f.text_field :name %>
  </div>

    <div class="field">
    <label for="user_image">ProfileImage</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %></div>

    <div class="field">
        <label for="introduction">Introduction</label>
   <%= f.text_area :introduction %>
  </div>
<div class="gender-field" style="display:inline-block";>
    <%= f.label :gender %><br />
    <%= f.label :man  %>
    <%= f.radio_button :gender, :man %>
    <%= f.label :woman  %>
    <%= f.radio_button :gender, :woman %>
    <%= f.label :other  %>
    <%= f.radio_button :gender, :other %>
</div>


<div class="field">
  <%= f.label :prefecture  %><br>
  <%= f.select :prefecture, User.prefectures.keys, {prompt: '選択してください'}, class: 'form-control  btn-default' ,style:"width:120px" %>
</div>

<div class="field">
  <%= f.label :age  %><br>
  <%= f.select :age, User.ages.keys, {prompt: '選択してください'}, class: 'form-control  btn-default' ,style:"width:120px" %>
</div>


<div class="actions" style="margin-top:20px";>
    <%= f.submit "Update User" %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= @user.errors.count %> errors.messages.not_saved</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  </div>
</div>
<% end %>
</div>
</div>
</div>
</body>

app/views/users/index.html.erb
<div class="container">
  <div class ="row">

<%= render 'users/prof', book: @book %>




<div class = "col-xs-9">
  <h1>Users</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% User.all.where.not(id: current_user.id).each do |user| %>
          <tr>
            <th></th>
            <th><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40', class: "img-circle" %></th>
            <th><%= user.name %></th>
            <th><%= link_to "Show", user_path(user.id) %></th>
            <th><%= "フォロー数: #{user.follower.count}" %><%= "フォロワー数: #{user.followered.count}" %></th>
            <th><% if current_user.following?(user) %>
                  <%= link_to 'フォロー解除', relationship_path(user.id), method: :DELETE, class:"btn btn-default" %>
                <% else %>
                  <%= link_to 'フォローする', relationships_path(user.id), method: :post, class:"btn btn-default" %>
                <% end %>
            </th>
　　　　　　</tr>
　　　　　<% end %>
　　　　</tbody>
　　</table>

app/views/users/search.html.erb
 <% if @user_or_book == "1" %>
    <h3>User</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>image</th>
                    <th>name</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <th></th>
                            <th>
                                <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '40x40', class: "img-circle" %></th>
                            <th><%= user.name %></th>
                            <th><%= link_to "Show", user_path(user.id) %></th>
                            <th><%= "フォロー数: #{user.follower.count}" %><%= "フォロワー数: #{user.followered.count}" %></th>
                            <th>
                                <% unless user == current_user %>
                                <% if current_user.following?(user) %>
                                    <%= link_to 'フォロー解除', relationship_path(user.id), method: :DELETE %>
                                <% else %>
                                    <%= link_to 'フォローする', relationships_path(user.id), method: :post %>
                                <% end %>
                                <% end %>
                            </th>
                        </tr>
                    <% end %>
                </tbody>
        </table>

<% elsif @user_or_book == "2" %>
    <h3>Book</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>userimage</th>
                    <th>title</th>
                    <th>body</th>
                </tr>
            </thead>
            <% @books.each do |book| %>
                <tbody>
                    <tr>
                        <th></th>
                        <th><%= link_to user_path(book.user) do %>
                                <%= attachment_image_tag book.user, :profile_image,format: 'jpeg', fallback: "no_image.jpg",size: "50x50", class: "img-circle"  %>
                            <% end %>
                        <th> <%= link_to book.title, book_path(book.id) %></th>
                        <th><%= book.body %></th>
                    </tr>
                </tbody>
            <% end %>
        </table>
<% end %>

app/views/users/show.html.erb
<p><%= flash[:notice] %></p>



<div class="container"style="width:850px;">
  <div class="row">
    <div class = "col-xs-3">

<h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg", class: "img-circle pull-left profile-img" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
       <tr>
        <th>gender</th>
        <th><%= @user.gender %></th>
      </tr>
      <th>age</th>
        <th><%= @user.age %></th>
      </tr>
      <tr>
        <th>prefecture</th>
        <th><%= @user.prefecture %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to " #{@user.follower.count}", follows_path(@user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to "#{@user.followered.count}", followers_path(@user.id) %></th>
      </tr>
      <tr>
        <th>
          <% unless @user == current_user %>
            <% if current_user.following?(@user) %>
              <%= link_to 'フォロー解除', relationship_path(@user.id), method: :DELETE, class:"btn btn-warning" %>
            <% else %>
              <%= link_to 'フォローする', relationships_path(@user.id), method: :POST, class:"btn btn-warning" %>
            <% end %>
            <% end %>
        </th>
      </tr>
    </tbody>
  </table>

    <% if @user.id == current_user.id %>
      <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <% else %>
      <%=  link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <% end %>



<h2>New book</h2>

  <%= form_for @book, url: books_path do |f| %>

<h4>Title</h4>
  <%= f.text_field :title %>

<h4>Body</h4>
  <%= f.text_area :body %><br>
    <%= f.submit "Create Book" %>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
   </div>



<div class = "col-xs-9">
<h1>Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Oponion</th>
      <th></th>
    </tr>
  </thead>

<tbody>
  <% @user.books.each do |a| %>
    <tr>
      <td>
        <%= link_to user_path(a.user.id) do %>
          <%= attachment_image_tag a.user, :profile_image,format: 'jpeg', fallback: "no_image.jpg",size: "50x50" , class: "img-circle"  %>
        <% end %>
      </td>
      <td><%= link_to a.title, book_path(a.id) %></td>

      <td><%= a.body %>
        <ul class="inline-meta">
          <li style="list-style: none; float:right;">
            <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color:#a9a9a9;"></span>
              <%= link_to "#{a.post_comments.count}", book_path(a.id) %>
          </li>
        </ul>
      </td>
  <% end %>
  <% end %>
</tbody>
</table>
</div>
</div>
</div>