config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "home/about" => 'homes#about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'books/new'
  get "top" => "books#top"
  get "users/:id/follows" => "relationships#follows", as: "follows"
  get "users/:id/followers" => "relationships#followers", as: "followers"
  post 'relationships/:id' => 'relationships#create', as: 'relationships'#user_isとfolloewd_idが結びついたもの,
  get "search" => "users#search", as: "search"

  resources :users, only: [:show, :new, :create, :index, :destroy, :update, :edit]
  resources :relationships, only: [:destroy,]

  resources :books, only: [:new, :create, :index, :edit, :show, :destroy, :update] do
  	resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :home, only: [:top, :about]

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
            favorites.where(user_id: user.id).exists?
    end

    validates :title, presence:true
    validates :body, length: { in: 1..200 }

    def Book.search(search, user_or_book, how_search)
    	    if user_or_book == "2"
    	    	if how_search == "1"
    	            Book.where(["title LIKE ?", "%#{search}%"])#name LIKE＝nameカラムを検索
    	        elsif how_search == "2"
                    Book.ere(['title LIKE ?', "%#{search}"])
                elsif how_search == "3"
                    Book.where(['title LIKE ?', "#{search}%"])
                elsif how_search == "4"
                    Book.where(['title LIKE ?', "#{search}"])
                else
    	            Book.all
    	        end
            end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def new
        @book = Book.new
        @books = Book.all
  end

  def create
        @book = Book.new(book_params)
        @user = current_user
        @books = Book.all
        @book.user_id = current_user.id#外部キー　book.user_idは空の状態
        if @book.save
        redirect_to book_path(@book.id)
        flash[:create] ="大成功2."
        else
        render action: :index
        end
  end

  def edit
        @book = Book.find(params[:id])

  end

  def index
        @user = current_user
    	   @books = Book.page(params[:page])
    	   @book = Book.new
        @t = Book.ransack(params[:q])
        @books = @t.result(distinct: true)
  end

  def show
        @new = Book.new
        @book = Book.find(params[:id])
        @user = @book.user
        @post_comment = PostComment.new
  end

  def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        redirect_to book_path(@book.id)
        flash[:update] ="大成功."
        else
        render action: :edit
        end
  end

  def destroy
        book = Book.find(params[:id]) #データ(レコード)を1件取得
        book.destroy #データ（レコード）を削除
        redirect_to books_path
  end

  


  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def correct_user
          book = Book.find(params[:id])
          if current_user.id != book.user.id
          redirect_to books_path
          end
    end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
  <% if book.favorited_by?(current_user) %>
    <li style="list-style: none; float: right;">
      <%= link_to book_favorites_path(book.id, q: "l"), method: :delete,remote: true do %>
        <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
          <%= book.favorites.count %>
      <% end %>
    </li>
  <% else %>
    <li style="list-style: none; float: right;">
      <%= link_to book_favorites_path(book.id,q: "l"), method: :post ,remote: true do %>
        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
          <%= book.favorites.count %>
    <% end %>
    </li>
  <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: @book.errors.count,
                 resource: @book.class.model_name.human.downcase)%>
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1>Editing Book</h1>
<div class = "container">
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %><br>
    <%= f.submit 'Update Book' %><br>

    <%= link_to "Show", book_path %>
	|
	<%= link_to "Back", books_path %>
	<% end %>
</div>

app/views/books/index.html.erb
<%= render 'users/prof', book: @book, user: @user %>



    <div class = "col-xs-9">
      <h1>Books</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
              <th></th>
            </tr>
          </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image,format: 'jpeg', fallback: "no_image.jpg",size: "50x50", class: "img-circle"  %>
                <% end %>
              </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                  <td>
                    <%= book.body %>
                  </td>
                    <td>
                      <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color:#a9a9a9;"></span>
                        <%= link_to "#{book.post_comments.count}", book_path(book.id) %>
                    </td>
                      <td>
                        <%= render 'books/list', book: book%>
                      </td>
            </tr>
          <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
  <div class ="container">

    <div class = "row">
  <div class = "col-xs-3">
<h1>Books</h1>

<table>
<thead>
<tr>
<th>Title</th>
<th>Body</th>
<th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>

  </tr>
  <% end %>
</tbody>
</table>
</div>






<div class = "col-xs-9">
<h1>NewBook</h1>

<%= form_for(@book) do |f| %>
 
    <h4>Title</h4>
    <%= f.text_field :title %>
 
 
    <h4>Opinion</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
<% end %>
</div>
</div>
</div>

app/views/books/show.html.erb
<p><%= flash[:create] %></p>
<p><%= flash[:update] %></p>

<div class="container">
  <div class ="row">
    <div class = "col-xs-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg", class: "img-circle pull-left profile-img" %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
                <th></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
                <th></th>
              </tr>
            </tbody>
          </table>
            <% if @user == current_user.id %>
              <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% else %>
              <%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            <% end %>


      <h1>Newbook</h1>
        <%= form_for(@new) do |f| %>
          <h4>Title</h4>
            <%= f.text_field :title %>
          <h4>Opinion</h4>
            <%= f.text_area :body %><br>
            <%= f.submit 'Create Book' %>
        <% end %>
    </div>


    <div class= "col-xs-9">
      <h2>Book detail</h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <td><%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag @book.user, :profile_image,format: 'jpeg', fallback: "no_image.jpg",size: "50x50" %><br>
                      <%= @user.name %>
                  <% end %>
              </td>
              <td><%= link_to @book.title, book_path %></td>
              <td><%= @book.body %></td>
              <td><% if @user == current_user %>
                    <%= link_to "Edit", edit_book_path %>
                  <% end %>
              </td>
              <td>
                <% if @user == current_user %>
                  <%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "Are you sure?" %>
                <% end %>
              </td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <li style="list-style: none; float: right;">
                    <%= link_to book_favorites_path(@book.id), method: :delete,remote: true do %>
                      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                         <%= @book.favorites.count %>
                    <% end %>
                  </li>
                <% else %>
                  <li style="list-style: none; float: right;">
                    <%= link_to book_favorites_path(@book.id), method: :post ,remote: true do %>
                       <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                          <%= @book.favorites.count %>
                    <% end %>
                  </li>
                <% end %>
              </td>
              <td>
                <div class="comment-list bt style-2" id="comments"></div>
                  <h2 class="comment-count" style="font-size: 15px;">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true" style="margin-right: 5px;"></span>
                      <%= @book.post_comments.count %></h2>
                        <ul style="list-style: none; margin-bottom: 10px;">
                          <% @book.post_comments.each do |post_comment| %>
                            <li class="comment" style="list-style: none;">
                              <div class="comment-text" style="margin-bottom: 10px;">
                                <div class="comment-author">
                                  <a href="#" class="link-author"><%= link_to post_comment.user.name %></a>
                                    <span class="comment-meta">
                                      <span class="comment-date"><%= post_comment.comment %></span>
                                    </span>
                                        <li style="list-style: none; float:right;">
                                          <% if post_comment.user_id == current_user.id %>
                                            <%= link_to "削除", book_post_comment_path(@book, post_comment), method: :delete %>
                                          <% end %>
                                        </li>
                                </div>
                                  <div style="margin-bottom: 10px;" class="comment-entry"><%= post_comment.created_at.strftime('%Y/%m/%d') %></div>
                              </div>
                            </li>
                          <% end %>
                        </ul>

                          <%= form_for [@book, @post_comment] do |f| %>
                            <div class="row">
                              <div class="col-sm-12"><%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %></div>
                            </div>
                              <%= f.submit "送信する", class: "btn btn-default  pull-right",style:"font-size: 5px; margin-top: 5px;" %>
                          <% end %>

              </td>
            </tr>
          </thead>
        </table>
    </div>
  </div>
</div>