config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "home/about" => 'homes#about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'books/new'
  get "top" => "books#top"
  get "users/:id/follows" => "relationships#follows", as: "follows"
  get "users/:id/followers" => "relationships#followers", as: "followers"
  post 'relationships/:id' => 'relationships#create', as: 'relationships'#user_isとfolloewd_idが結びついたもの,
  get "search" => "users#search", as: "search"

  resources :users, only: [:show, :new, :create, :index, :destroy, :update, :edit]
  resources :relationships, only: [:destroy,]

  resources :books, only: [:new, :create, :index, :edit, :show, :destroy, :update] do
  	resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :home, only: [:top, :about]

end

app/views/layouts/_header.html.erb
<header class="navbar" style="background-color:#dcdcdc;">
    <div class="container">
      <span style="color:#808080; padding-top:50px; font-size:40px;">Bookers</span>
        <div id="container">
          <div class="theTarget" style="width:400px,height:200px">
            <div class="image1"></div>
            <div class="image2"></div>
            <div class="image3"></div>
            <div class="image4"></div>
            <div class="image5"></div>
          </div>
        </div>


         <nav>
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn" style="color:#c0c0c0;">
              <% if user_signed_in? %>
                <li><%= link_to 'Home', user_path(current_user.id),class: 'glyphicon glyphicon-home home' %></li>
                <li><%= link_to "Users", users_path,class: 'glyphicon glyphicon-user users'  %></li>
                <li><%= link_to ' Books',books_path ,class: 'glyphicon glyphicon-book books'%></li>
                <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>

              <% else %>
                <li><%= link_to ' Home',root_path,class: 'glyphicon glyphicon-home home' %></li>
                <li><%= link_to ' About',home_about_path,class: 'glyphicon glyphicon-link about' %></li>
                <li><%= link_to ' sign up', new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up' %></li>
                <li><%= link_to ' login', new_user_session_path ,class: 'glyphicon glyphicon-log-in sign_in'%></li>
              <% end %>
            </ul>
　　　　　　</nav>
　　　　　</div>
        <div class="search" style="margin-left: 20px;">
          <%= form_tag(search_path, :method => 'get') do %>
            <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%>
            <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
            <%= text_field_tag :search %>
            <%= submit_tag 'Search', :name => nil %>
          <% end %>
        </div>
　</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <title>Bookers3</title>
                <%= csrf_meta_tags %>
                <%= csp_meta_tag %>
                <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        </head>
        <body>
          <%= render 'layouts/header' %>
            <div class='body'>
              <div class="container">
                  <div class="row">
　　　                <%= yield %>
                  </div>
              </div>

            <footer>
              <div class="container">
                <div class="row">
                  <div class="col-xs-3 col-xs-offset-9">
                    <p>CopyRight Infratop.inc</p>
                  </div>
                </div>
              </div>
            </footer>
            </div>
    </html>
 